BEGIN TRANSACTION;
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (1029471,32,0,511,4129,1800,500,4,16,1,269484032);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (1904632,32,0,511,8388641,2800,1800,5,16,32,1024);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (2309538,32,0,511,33,100,100,1,16,2,1024);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (10238456,32,0,511,33,1300,100,4,16,8,1064960);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12095471,32,0,511,2,0,0,0,0,0,1049088);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12486783,32,0,511,4129,0,0,1,16,8,1051136);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12562083,32,0,511,67108897,2800,7,3,16,32,131200);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12847632,32,0,511,12321,900,2200,5,16,8,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12875538,32,0,511,8388641,1900,400,3,16,1,132096);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (12984761,32,0,511,8388641,1900,2700,4,16,1,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (13748644,32,0,511,33,1300,600,3,16,1,1049088);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (13982763,32,0,511,4129,1200,700,3,16,2,1312768);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (18354834,32,0,511,1048580,0,0,0,0,0,65537);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (19385762,32,0,511,4129,800,300,2,16,2,131072);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (21746298,32,0,511,65538,0,0,0,0,0,1024);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (23548139,32,0,511,33,700,300,2,16,1,262147);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (29013462,32,0,511,4,0,0,0,0,0,128);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (29364485,32,0,511,524290,0,0,0,0,0,132096);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (34729393,32,0,511,67108897,1800,40,2,16,2,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (102947376,32,0,511,8388641,2400,1100,4,16,32,3);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (119283618,32,0,511,33,1000,200,3,16,1,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (120273771,32,0,511,4129,0,0,1,16,4,1048579);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (127345284,32,0,511,8225,2800,1700,8,16,8,1179648);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (127732763,32,0,511,8225,3200,2000,9,16,1,514);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (137472478,32,0,511,131076,0,0,0,0,0,66560);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (173263289,32,0,511,131074,0,0,0,0,0,1049088);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (173286429,32,0,511,8225,-2,-2,10,16,32,1049088);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (173516394,32,0,511,33,200,100,1,16,4,1073741824);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (173816518,32,0,511,8388641,0,2200,3,16,1,512);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (178267253,32,0,511,131074,0,0,0,0,0,512);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (182735322,32,0,511,12321,2100,500,4,16,4,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (183636152,32,0,511,8225,2600,1700,7,16,4,32);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (183645272,32,0,511,8225,2300,800,6,16,2,1048576);
INSERT INTO "datas" ("id","ot","alias","setcode","type","atk","def","level","race","attribute","category") VALUES (190375782,32,0,511,67108897,2000,34,2,16,4,32768);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (1029471,'Necromorph Slasher','When this card is normal or special summoned: place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. When this card is normal summoned: you can special summon a level 4 or lower "Necromorph" monster from your hand.','"Necromorph Slasher" was normal summoned, Special summon a monster from hand?','Added 1 Necro counter','Prevent destruction of "Necromorph Slasher"?','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (1904632,'Necromorph Tormentor','3 level 5 monsters
You can also Xyz this card by using "Necromorph" rank 4 Xyz monster you control as material (Xyz materials attached to that monster also become Xyz materials for this card). When this card is special summoned, place 3 Necro counters in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. You can dettach 1 Xyz material from this card and remove 2 Necro counters from your field; it gains 400 attack for each Necro counter it has and is unaffected by your opponent''s activated effects until the end of the next turn.','Select a Xyz monster to use as Xyz Material.','Added 3 Necro counters','Prevent destruction of "Necromorph Tormentor"?','Inmune to activated effects','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (2309538,'Necromorph Swarmer','While this card is in your hand or field: Once per chain, (Quick Effect): Equip this card to a monster on your opponent''s side of the field and treat it as an Equip Card, its attack and deffense becomes 0. If this card is sent to the GY while in the Spell & Trap Zone: draw 1 card. You can only use this effect of "Necromorph Swarmer" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (10238456,'Necromorph Leaper','When this card is normal or special summoned: place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. This card can attack directly. If this card deals battle damage: target 1 card on the field; return that target to the hand. If a "Necromorph" monster is normal summoned: you can special summon this card from your hand.','','Added 1 Necro counter','Prevent destruction of "Necromorph Leaper"?','After Damage Calculation, Activate the effect of "Necromorph Leaper"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12095471,'Necromorph Ambush','If you control no monsters: Special summon 1 "Necromorph" monster with a different name from the cards in your GY. You can banish this card from your GY; spceial summon up to 2 Zombie monsetrs from your GY in deffense position. You can only activate each effect of "Necromorph Ambush" once per turn and only once that turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12486783,'Necromorph Wheezer','All non-Zombie monsters on the field lose 500 ATK/DEF. When this card is normal or special summoned: special summon 1 level 3 or less "Necromorph" monster from your deck in deffense position, except "Necromorph Wheezer", also for the rest of this turn, you can only special summon Zombie monsters. You can only use this effect of "Necromorph Wheezer" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12562083,'Necromorph Tripod','3 Fusion, Synchro, Xyz or Link Zombie monsters
When this card is special summoned, place 3 Necro counters in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. While this card has Necro counters, (Quick Effect): remove 2 Necro counters from your field, then target 1 card on the field or GY; banish it, and if you do, its effects are negated until the end phase, you can only use this effect of "Necromorph Tripod" once per turn.',NULL,'Added 3 Necro counters','Prevent destruction of "Necromorph Tripod"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12847632,'Necromorph Infector','1 Zombie Tuner + 1+ non-Tuner Zombie monsters
When this card is special summoned, place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. You can remove 1 Necro counter from your field; special summon 1 monster from either graveyard. It becomes Zombie-Type and you can only special summon Zombie monsters for the rest of the turn. You can only use this effect of "Necromorph Infector" once per turn.','','Added 1 Necro counter','Prevent destruction of "Necromorph Infector"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12875538,'Necromorph Spitter','2 Level 3 Zombie monsters
When this card is special summoned, place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. When your opponent activates a monster effect (Quick Effect): Detach 1 Xyz material from this card and remove 1 Necro counter from the filed; negate the activation, then, if that monster is on the field, its ATK becomes half its original ATK until the end of this turn. You can only use this effect of "Necromorph Spitter" once per turn.',NULL,'Added 1 Necro counter','Prevent destruction of "Necromorph Spitter"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (12984761,'Necromorph Guardian','3 level 4 monsters
You can also Xyz this card by using "Necromorph Inmature Guardian" as Xyz material (Xyz materials attached to that monster also become Xyz materials for this card). You can detach all Xyz materials from this card, then summon "Necromorph Pod" from your hand, deck, or graveyard up to the number of materials used. For the rest of the turn, you can only special summon zombie monsters. You can only use this effect of "Necromorph Guardian" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (13748644,'Necromorph Stalker','When you control only "Necromorph" monsters (min. 1), (Quick effect): Special summon this card from your hand. If this card is normal or special summoned: Target 1 other card in this card''s column; destroy it. You can only use each effect of "Necromorph Stalker" once per turn.','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (13982763,'Necromorph Puker','If this card is in your hand or GY: You can target 1 level 2 or higher "Necromorph" monster you control; reduce its level by 1, and if you do, special summon this card and deal 800 damage to your opponent''s life points. You can only use this effect of "Necromorph Puker" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (18354834,'Necromorph Cyst','When a monster(s) would be Special Summoned, OR a monster effect would be activated while you control a "Necromorph" monster: negate the Summon or activation, and if you do, destroy that card. If this card is in your GY: you can remove 1 Necro counter from your field; set this card, but banish it when it leaves the field.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (19385762,'Necromorph Lurker','While this card is in your hand or field (Quick Effect): Equip this card to a monster on your opponent''s side of the field and treat it as an Equip Card, its effects are negated. If this card is sent to the GY while in the Spell & Trap Zone: special summon it in Defense Position. You can only use each effect of "Necromorph Lurker" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (21746298,'Necromorph Bio-Enhancement','Target 1 "Necromorph" monster you control; it gains Necro counters equal to its Level/Rank/Link rating, then it gains 500 ATK for each Necro counter it has until the end of this turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (23548139,'Necromorph Pod','When an opponent''s monster declares an attack: You can special summon this card from your hand in attack position, and if you do, change the attack target to this card and proceed to damage calculation. Your opponent takes any battle damage from battles involving this card.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (29013462,'Necromorph Drag Tentacle','Banish 1 card on the field. If this set card is destroyed by a card effect: You can target up to 2 "Necromorph" cards in your GY except "Necromorph Drag Tentacle"; add them to your hand. You can only use this effect of "Necromorph Drag Tentacle" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (29364485,'Necromorph Planet Aegis VII','All non-Zombie monsters on the field lose 300 ATK/DEF. During each standby phase place Necro counters in this card equal to the amount of "Necromorph" monsters you control. When your opponent activates a card(s) you control: (Quick Effect): Remove 2 Necro counters from your field; negate that effect, and if you do, destroy that card. You can only use this effect of "Necromorph Planet Aegis VII" up to twice per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (34729393,'Necromorph Pregnant','2 Zombie monsters
When this card is special summoned, add 1 Necro counter to this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. If this link summoned card is sent to the GY while you have Necro counters on your field:  special summon up to 3 "Necromorph Swarmer" from your hand, deck or GY, but after this effect resolves you can only special summon Zombie monsters for the rest of this turn. You can only use this effect of  "Necromorph Pregnant" once per turn.','','Added 1 Necro counter','Prevent destruction of "Necromorph Pregnant"?','','','','','','','','','','','','','');
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (102947376,'Necromorph Brute','2 level 4 Zombie monsters
When this card is special summoned, add 2 Necro counters to this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. When your opponent activates a Spell/Trap card or effect (Quick Effect): detach 1 Xyz material from this card and remove 1 Necro counter from the field; negate its activation and destroy it, and if you do, send the top 3 cards of your opponent''s deck to the graveyard. You can only activate this effect of "Necromorph Brute" once per turn.','','Added 2 Necro counters','Prevent destruction of "Necromorph Brute"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (119283618,'Necromorph Pack','If this card is normal or special summoned: you can special summon 1 "Necromorph Pack" from your hand, deck or GY. You can only use this effect of "Necromorph Pack" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (120273771,'Necromorph Exploder','If your opponent controls more monsters than you do, you can special summon this card from your hand. You can only special summon "Necromorph Exploder" once per turn this way. (Quick Effect): destroy all cards on this card''s column. You can only use this effect of "Necromorph Exploder" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (127345284,'Necromorph Leviathan','1 Zombie Tuner + 1+ non-Tuner Zombie monsters
When this card is summoned, place 3 Necro counters in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. If this card is Synchro summoned: you can activate one of the following effects once per turn and only once that turn:
-Special summon 1 "Necromorph Wheezer" from your deck, hand or graveyard.
-Negate the effect of all non-Zombie monsters currently on the field until the end of this turn.','Special summon 1 "Necromorph Wheezer" from your deck, hand or GY.','Negate the effect of all non-Zombie monsters currently on the field.','Added 3 Necro counters','Prevent destruction of "Necromorph Leviathan"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (127732763,'Necromorph Slug','1 Zombie Tuner + 1+ non-Tuner Zombie monsters
When this card is special summoned, place 3 Necro counters in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. If this card is synchro summoned: you can destroy all Spells and Traps on the field. Your opponent cannot activate cards or effects in response to this effect''s activation. You can remove 2 Necro counters from your field; add 1 "Necromorph" continous spell from your deck to your hand. You can only activate each effect of "Necromorph Slug" once per turn.',NULL,'Added 3 Necro counters','Prevent destruction of "Necromorph Slug"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (137472478,'Necromorph Horde','This card can only be activated when you control more monsters than your opponent. Your "Necromorph" monsters gain 100 ATK for each Necro counter on the field. Banished monsters and in the GY cannot activate their effects except for zombie monsters. During your end phase: if you control less monsters than your opponent: destroy this card.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (173263289,'The Necromorph Marker','You can discard 1 card from your hand; special summon 1 "Necromorph" monster from your GY. When this card is sent from the field to the GY: add 1 "Necromorph" spell or trap from your deck to your hand except  "The Necromorph Marker". You can only activate each of the effects of "The Necromorph Marker" once per turn.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (173286429,'Necromorph Hive Mind','"Necromorph" Tuner + 1 or more non-Tuner Zombie monsters
When this card is special summoned, place 5 Necro counters in this card. When this card would be detroyed, you can remove 1 Necro counter from this card instead. This card''s ATK/DEF become the amount of Necro counters on your field x 600. You can only activate the following effects of "Necromorph Hive Mind" once per turn. If this card is sent from the field to the GY: add 1 "The Necromorph Marker" from your deck to your hand. (Quick Effect): Remove 2 Necro counters from your field; special summon 1 "Necromorph" monster from your  GY.','Special summon a "Necromorph" monster from your graveyard.','Added 5 Necro counters','Prevent destruction of "Necromorph Hive Mind"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (173516394,'Necromorph Divider Components','You can Tribute 2 Zombie monsters, target 1 monster on your opponent''s side of the field; its type becomes Zombie, then equip this card to that monster and treat it as an Equip Card. Take control of the equipped monster.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (173816518,'Necromorph Inmature Guardian','2 level 3 monsters
You can dettach 1 Xyz material from this card; add 1 "Necromorph" monster from your deck to your hand.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (178267253,'Necromorph Ship USG Ishimura','When this card is activated: you can activate 1 "Necromorph Planet Aegis VII" from your deck or GY and then place 2 necro counters in this card. "Necromorph Planet Aegis VII" cannot be destroyed while this card is on the field. When this card would be destroyed, remove 2 Necro counters from this card instead. During the end phase add Necro counters to this card up to the number of "Necromorph" monsters you control. You can only activate 1 "Necromorph Ship USG Ishimura" per turn.','Activate "Necromorph Planet Aegis VII"  from deck or GY?','Prevent destruction of "Necromorph Ship USG Ishimura"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (182735322,'Necromorph Divider','1 Zombie Tuner + 1+ non-Tuner monsters
When this card is special summoned, place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. If this card is sent from the field to the GY: you can special summon 3 "Necromorph Divider Components" from your hand, deck or GY, but you can only special summon Zombie monsters for the rest of this turn. You can only use this effect of "Necromorph Divider" once per turn.','','Added 1 Necro counter','Prevent destruction of "Necromorph Divider"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (183636152,'Necromorph Nest','1 Zombie Tuner + 1 or more non-Tuner Zombie monsters
When this card is special summoned, add 2 Necro counters to this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. (Quick Effect): You can remove 2 Necro counters from the field; return 1 card from the field to the hand, you can only use this effect of "Necromorph Nest" once per turn.','','Added 2 Necro counters','Prevent destruction of "Necromorph Nest"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (183645272,'Necromorph Hunter','1 Tuner + 1+ non-Tuner monsters
When this card is special summoned, place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. During the standby phase, if this card is in the GY: you can special summon it. You can only control 1 "Necromorph Hunter".','','Added 1 Necro counter','Prevent destruction of "Necromorph Hunter"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "texts" ("id","name","desc","str1","str2","str3","str4","str5","str6","str7","str8","str9","str10","str11","str12","str13","str14","str15","str16") VALUES (190375782,'Necromorph Twitcher','2 Zombie monsters
2 Zombie monsters
When this card is special summoned, place 1 Necro counter in this card. When this card would be destroyed, you can remove 1 Necro counter from this card instead. This card can attack up to the number of Necro counters on your field (Maximum 3 times) during each Battle Phase.',NULL,'Added 1 Necro counter','Prevent destruction of "Necromorph Twitcher"?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
COMMIT;
